### PR TITLE
add support for TLS encrypted TCP transport

### PR DESCRIPTION
**Pull request by sethb0**
Added a `Transport.Tls` option

### CODE REVIEW

**Comment by paulgrove** [comment]
Apologies for not seeing this pull request for quite some time.  I don't recall seeing notification for this in github - but it was also only a few days before the birth of my daughter, so maybe I was unfocused at the time.

This PR fails CI tests because I'm still supporting 0.10.x of nodejs.

I have no reason to maintain support for this version so I will look to merge after a closer review  and then do a major version bump while dropping support for node 0.10.x.

Thanks for the PR - and Apologies again for the delay.

**Comment by hideflolife** [comment]
@paulgrove what's the status of this? Can I help you incorporate this pr, as it would be useful for something I'm trying to do in v12.x

**Comment by lironpx** [comment]
@paulgrove Do you need help solving this PR issues? I need this feature too

**Comment by bluEEil** [comment]
@paulgrove 
I also needed tls for something I'm working on. I started by implementing this on a local copy of the package in my work space, but this PR looks much better and is very needed. This option is also available in other packages like (I inspired my own version of this package with tls on this):
https://github.com/cyamato/SyslogPro/blob/master/index.js

But I prefer working with this package since it's more straight forward on other regards.
Is there ETA on when this is going to be merged?

**Pull request merged**
