### PR TITLE
appName, dateFormatter params for RFC5424 output; error checking around UDP connection

### PR DESCRIPTION
**Pull request by mividtim**
Hi Paul,

Thanks for reaching out to me about the rfc5424 feature addition to the original `node-syslog-client` code base.  And I'm sorry it took so long to reply: I'm using this in a production code base at work, and wanted to wait until I was submitting a PR for work to finalize my changes before submitting them back to you.  Still, I could have and should have responded to you earlier, either way.

I do desire to sunset my own fork, and hopefully then you won't get any more haggling over code you didn't write going forward.  I do need to add three small features in order to use your fork and sunset my own.  I hope you'll consider merging this PR, so that the community of users can benefit.

- Optional `appName` option on either `createClient()` or `log()`, for specifying rfc5424 `APP-NAME` field (defaults to original behavior of grabbing the last part of `process.title`)
- Optional `dateFormatter` function option on `createClient()` (affects rfc5424 only), to override the default (and original) behavior of using `date.toISOString()`
- Bugfix: `try`/`catch` wrapper around initial UDP connection, so that it emits an error which the caller can catch (for retries)

If you don't want these features, please let me know, so that I can formally take ownership of my fork and remove your email from the README.

Cheers and thanks,

Tim

### CODE REVIEW

**Comment by paulgrove** [comment]
No problem at all, My only concern is that I would like to keep the default to rfc3164.

See my comment in the diff for details.

I can see that the way it was previously implemented was problematic anyway so I understand your removal of the original line.

**Comment by mividtim** [comment]
Hi Paul,

Yeah that was a bit problematic.  I just pushed up what I think is a good
fix.  It won't work if you pass in a string value of "false", but that's a
corner case I think we can live without.  If it's a boolean, we use it.  If
not, we go with true.

Please let me know your thoughts.

Cheers,

Tim

**Comment by paulgrove** [comment]
Anything outside of setting it to a boolean is outside of the documented API anyway, so no problems from me.

I think I'm otherwise happy, thanks for your efforts here, I'm going to merge this now.  Expect an update on npm later this week (it will go through the test framework of our product as well).

And thanks for responding after I reached out!

**Comment by mividtim** [comment]
Hi Paul,

Could you please publish this to npm so I can use it without a git
reference?

Thanks!

Tim

**Comment by paulgrove** [comment]
Done!

Sorry I let this slip my mind, apologies for the delay.

Cheers,
Paul

**Pull request merged**
